package tudelft.ewi.cse2000.ruisdael.monitoring.service;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch._types.SortOptions;
import co.elastic.clients.elasticsearch._types.SortOrder;
import co.elastic.clients.elasticsearch.core.SearchResponse;
import co.elastic.clients.elasticsearch.core.search.Hit;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tudelft.ewi.cse2000.ruisdael.monitoring.component.DeviceDataConverter;
import tudelft.ewi.cse2000.ruisdael.monitoring.entity.Device;

/**
 * Service class for Elasticsearch operations.
 */
@Service
public class ElasticsearchService {
    private static final String INDEXPREFIX = "collector_";

    private final ElasticsearchClient client;

    /**
     * Constructs an instance of ElasticsearchService with the specified Elasticsearch client.
     *
     * @param client The ElasticsearchClient dependency injected automatically by the Spring framework.
     */
    @Autowired
    public ElasticsearchService(ElasticsearchClient client) {
        this.client = client;
    }

    /**
     * Queries elastic to receive the latest data on a given node, and converts this to a @{@link Device}.
     * @param nodeIndexName The name of the node to look up data for.
     * @return A {@link Device} object with the latest data, or null if no such device exists, or no data is available.
     */
    public Device getDeviceDetailsFromName(String nodeIndexName) {
        try {
            SearchResponse<Map> response = client.search(s -> s
                    .index(INDEXPREFIX + nodeIndexName)
                    .sort(new SortOptions.Builder().field(field -> field.field("@timestamp").order(SortOrder.Desc)).build()),
                    Map.class);

            List<Hit<Map>> allHits = response.hits().hits();

            if (allHits.size() == 0) { //No results
                return null;
            }

            Hit<Map> lastHit = allHits.get(0); //Get latest result
            String deviceName = lastHit.index().replace(INDEXPREFIX, "");

            return DeviceDataConverter.createDeviceFromElasticData(deviceName, true, lastHit.source());
        } catch (Exception e) { //IOException or IllegalArgumentException
            return null;
        }
    }

    /**
     * Queries elastic to receive data on all nodes, but the order of nodes is not guaranteed.
     * @return A list of all nodes with the latest data in a {@link Device} object.
     */
    public List<Device> getAllDevices() {
        List<String> distinctIndexNames = getDistinctIndexNames();

        return distinctIndexNames.stream()
                .map(this::getDeviceDetailsFromName)
                .toList();
    }

    /**
     * Retrieves a list of distinct index names generated by the monitoring software.
     *
     * @return A list of distinct index names.
     */
    public List<String> getDistinctIndexNames() {
        try {
            List<String> uniqueIndices = new ArrayList<>();

            client.indices().stats().indices().keySet().forEach(index -> {
                if (index.startsWith(INDEXPREFIX)) {
                    uniqueIndices.add(index.replaceFirst(INDEXPREFIX, ""));
                }
            });

            return uniqueIndices;
        } catch (Exception e) {
            e.printStackTrace();
            return List.of();
        }
    }

}
