image: eclipse-temurin:17.0.7_7-jdk

stages:
  - build
  - static-validation
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  needs: []
  script:
    ./gradlew --build-cache :server:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

checkstyle:
  stage: static-validation
  needs: [build]
  script: ./gradlew :server:checkstyleMain :server:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true
  artifacts:
    paths:
      [ "build/reports/checkstyle/main.xml",
        "build/reports/checkstyle/test.xml" ]

pmd:
  stage: static-validation
  needs: [build]
  script: ./gradlew :server:pmdMain :server:pmdTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  artifacts:
    paths:
      [ "build/reports/pmd/main.xml",
        "build/reports/pmd/test.xml" ]

junit-jacoco:
  stage: test
  needs: [build]
  script:
    - ./gradlew :server:test :server:jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

pitest:
  stage: test
  needs: [junit-jacoco]
  script:
    - ./gradlew :server:pitest
