INSERT INTO USERS (ENABLED, IS_ADMIN, IS_USER, PASSWORD, TOKEN_EXPIRED, USERNAME)
SELECT ENABLED, IS_ADMIN, IS_USER, PASSWORD, TOKEN_EXPIRED, USERNAME
FROM (SELECT FALSE AS Enabled, FALSE AS Is_admin, TRUE AS Is_user, '$2a$10$Dhx1wTGoklbiWZtzyHhKbe.gqOQsZ7OZq7GXaPVdsyrgJy3XU1gSC' AS Password, TRUE as Token_expired, 'guest' AS Username
      UNION ALL
      SELECT TRUE, TRUE, TRUE, '$2a$10$hffegIpU8m4XY0HEnPy94uLtCXwBbcYBcFYHxINkJF37sc4NH4LLK', TRUE, 'admin') sub
WHERE NOT EXISTS(SELECT 1
                 FROM USERS u
                 WHERE sub.Username = u.USERNAME);
